### ISSUE TITLE
Change action button

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Trade-Site#10]
Change the action button to that - 
![unnamed 3](https://cloud.githubusercontent.com/assets/26923359/25564238/8a1ba78a-2db7-11e7-94e6-be67291d21cb.png)

**Comment by MeanEYE** [comment]
@talovdat does this new button needs to be included beside every other button.

**Comment by talovdat** [comment]
Yes.

**Comment by iliyaM** [comment]
Done.
