### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Trade-Site#11]
Change the favicon in the explorer as it was in chrome.

**Comment by MeanEYE** [comment]
@iliyaM just confirm behavior here. Am not entirely sure this is an issue at all. If they are using too old version of IE that could be the issue. Check if favicon is present and being loaded in network tab.

**Comment by iliyaM** [comment]
after clearing cache storage and cache application tried to refresh and did see favicon loading. 
also my local favicon is for zemma

![screenshot from 2017-05-04 18-13-33](https://cloud.githubusercontent.com/assets/20294485/25710607/6820db6e-30f5-11e7-9567-d6e7127016c6.png)

**Comment by MeanEYE** [comment]
![image](https://cloud.githubusercontent.com/assets/1911594/25780839/37082316-332f-11e7-9f00-b59df4b17e87.png)
Icons are loaded once and cached. It takes a lot of effort to get them out. Clearing cache means nothing for `favicons`. On the other hand, icon looks as good as it needs to be to me. I suggest either testing with new device or through `ngrok` where browser doesn't have cache for URL.

**Comment by MeanEYE** [comment]
No issue here. I've checked the site and works as expected.
