### ISSUE TITLE
Terms and conditions approval button

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Trade-Site#17]
At the popup, next to the text, there should be a small aproval button set as defult marked V , but yet changeable (remove the V by clikcing on it.)

![capture](https://cloud.githubusercontent.com/assets/26923359/25803795/4a2c299c-3401-11e7-87f0-2ac3034abcfa.PNG)

**Comment by MeanEYE** [comment]
@talovdat we need to know `fieldname` for this checkbox since data is being sent from our site to theirs.

**Comment by talovdat** [comment]
@MeanEYE Is the code that i sent you via E mail is good for the 'fieldname'  you comment above?

**Comment by MeanEYE** [comment]
I didn't get any email containing `field name`.

**Comment by iliyaM** [comment]
I was told that he wanted to use our contact_form. 
can this issue be closed?

**Comment by MeanEYE** [comment]
Don't touch it yet. I have no idea what he wants, and something tells me he has no idea what he wants either.

**Comment by eyalway2cu** [comment]
finding out what field and value he is looking to get on the salesforce side, will update

**Comment by MeanEYE** [comment]
@eyalway2cu was that a question or a statement? We do have some `CampaignID` that was sent unrelated to anything. Perhaps that's the thing you are looking for?

**Comment by eyalway2cu** [comment]
@MeanEYE no, I did this for his other page, there is a field (with the very clear name) "00Nb000000AOOfb" which has a value of "מאושר" which means approved in Hebrew. I asked him to tell me what happens when someone does not check that box, did not receive a reply yet.

**Comment by eyalway2cu** [comment]
@MeanEYE  I got an answer from the client finally.
We need to add a checkbox, the field name is 00Nb000000AOOfb. If the box is checked we need to use the value "מאושר", if its not checked we send an empty field.

**Comment by MeanEYE** [comment]
Why sending specific value and not just a Boolean value?

**Comment by eyalway2cu** [comment]
Because they are a bunch of retards that do not know how to configure a Boolean field in Salesforce.... im just assuming but something tells me I am right.

**Comment by MeanEYE** [comment]
I have to check if Caracal supports this.

**Comment by MeanEYE** [comment]
Actually, this form is not built in Caracal's Contact Form, right?

**Comment by eyalway2cu** [comment]
Yeah, its hard coded, I think you can solve this using JS.

**Comment by MeanEYE** [comment]
And last time when I explicitly asked for a complete form, this didn't ring a bell? JavaScript is not needed, HTML alone has enough features to solve this issue.

@talovdat you should be made to solve this issue now. I was explicit with my requirement that _a complete form_ needs to be sent to us. This subsequent modification is simply not acceptable and is a waste of time for us.

@iliyaM in that form, create new field like we usually do:
```html
<label>
<input type="checkbox" name="00Nb000000AOOfb" value="מאושר"/>
<span>...</span>
</label>
```

**Comment by iliyaM** [comment]
![screenshot from 2017-06-06 14-26-43](https://cloud.githubusercontent.com/assets/20294485/26827069/362e37da-4ac4-11e7-9d1b-4a30e85c2707.png)

like this? 
what is the span for?

**Comment by MeanEYE** [comment]
For the text of the checkbox of course. What kind of a question is that? And why did you add id?
