### ISSUE TITLE
Sending form fixed code.

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Trade-Site#20]
Apply the fixed code for the popup sending form.
Code in Mladen and Ilya's inbox.

**Comment by MeanEYE** [comment]
@iliyaM this code should be used as is, without any changes. I want to avoid situation where he wants us to change single character and move it somewhere else.

**Comment by talovdat** [comment]
Attachments of fixed code in MeanEYE and Iliya's inbox.
