### ISSUE TITLE
White page when sending form.

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Trade-Site#21]
When you click on 'send form' in the light box (popup) the page goes white.
There should be a small approval popup that the form has been sent.

**Comment by iliyaM** [comment]
We have no form on this site. and no sendgrid. in other words the form you are referring to is the clients.
no idea. sorry

**Comment by MeanEYE** [comment]
@iliyaM create `/thank-you` page or something like that. Then configure form `retURL` to be `URL::make()` to that `/thank-you`. That way after submission their system should return us to thank you page.
