### ISSUE TITLE
Change 'open account' nav menu text link

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Trade-Site#22]
In nav bar you have link to 'open account' change it to say
"לקבלת הצעה"
The behavior should stay the same, just text.

**Comment by MeanEYE** [comment]
How many times are we suppose to change this?

**Comment by talovdat** [comment]
Just this once.

בתאריך 29 במאי 2017 02:04 PM,‏ "Mladen Mijatov" <notifications@github.com>
כתב:
