### ISSUE TITLE
Align button to text.

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Trade-Site#8]
Need to aline the text and the button. 
![unnamed 1](https://cloud.githubusercontent.com/assets/26923359/25564147/ea307914-2db4-11e7-8bb8-d8444cdd4f70.jpg)

**Comment by MeanEYE** [comment]
I think this one is fixed already but I am assigning @iliyaM anyway.

**Comment by iliyaM** [comment]
its done. its aline
